# Generated by Django 4.2.4 on 2024-09-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_catagery_user_subcatagery_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcatagery',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
